# Generated by Django 4.2 on 2024-09-02 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppEntrega3', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pelicula',
            new_name='Musica',
        ),
    ]
