# Generated by Django 4.2 on 2024-09-06 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppEntrega3', '0002_rename_pelicula_musica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musica',
            name='genero',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='musica',
            name='nombre',
            field=models.CharField(max_length=40),
        ),
    ]
